/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pe.edu.utp.poo.application.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDateTime;
import javax.swing.Timer;
import pe.edu.utp.poo.application.common.Util;

/**
 *
 * @author manuelguarniz
 */
public class UIMainMenu extends javax.swing.JFrame {
    MenuActionListener menuActionListener;

    /**
     * Creates new form ViewMainMenu
     */
    public UIMainMenu() {
        initComponents();
        configMenuItems();
        configTimer();
    }
    
    private void configMenuItems() {
        menuActionListener = new MenuActionListener(jdpMain);
        jmiAcercaDe.addActionListener(menuActionListener);
        jmiBoleteria.addActionListener(menuActionListener);
        jmiPeliculas.addActionListener(menuActionListener);
        jmiSalir.addActionListener(menuActionListener);
        jmiUsuarios.addActionListener(menuActionListener);
    }
    
    private void configTimer() {
        Timer timer = new Timer(1000, actionListenerTimer());
        timer.setRepeats(true);
        timer.start();
    }
    
    private ActionListener actionListenerTimer() {
        return (ActionEvent e) -> {
            setLocalTime();
        };
    }
    
    private void setLocalTime() {
        LocalDateTime now = LocalDateTime.now();
        lblLocalTime.setText(Util.parseDate(now));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpMain = new javax.swing.JDesktopPane();
        jpFooter = new javax.swing.JPanel();
        jpAppName = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpProgressBar = new javax.swing.JPanel();
        jpLocaltime = new javax.swing.JPanel();
        lblLocalTime = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmuPerfil = new javax.swing.JMenuItem();
        jmiSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiUsuarios = new javax.swing.JMenuItem();
        jmiPeliculas = new javax.swing.JMenuItem();
        jmiBoleteria = new javax.swing.JMenu();
        jmHelp = new javax.swing.JMenu();
        jmiAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));

        javax.swing.GroupLayout jdpMainLayout = new javax.swing.GroupLayout(jdpMain);
        jdpMain.setLayout(jdpMainLayout);
        jdpMainLayout.setHorizontalGroup(
            jdpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jdpMainLayout.setVerticalGroup(
            jdpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
        );

        jLabel1.setText("UTP ® 2024");

        javax.swing.GroupLayout jpAppNameLayout = new javax.swing.GroupLayout(jpAppName);
        jpAppName.setLayout(jpAppNameLayout);
        jpAppNameLayout.setHorizontalGroup(
            jpAppNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAppNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jpAppNameLayout.setVerticalGroup(
            jpAppNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAppNameLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpProgressBarLayout = new javax.swing.GroupLayout(jpProgressBar);
        jpProgressBar.setLayout(jpProgressBarLayout);
        jpProgressBarLayout.setHorizontalGroup(
            jpProgressBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 879, Short.MAX_VALUE)
        );
        jpProgressBarLayout.setVerticalGroup(
            jpProgressBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblLocalTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLocalTime.setText("YYYY-MM-DD HH:mm:ss");

        javax.swing.GroupLayout jpLocaltimeLayout = new javax.swing.GroupLayout(jpLocaltime);
        jpLocaltime.setLayout(jpLocaltimeLayout);
        jpLocaltimeLayout.setHorizontalGroup(
            jpLocaltimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLocalTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jpLocaltimeLayout.setVerticalGroup(
            jpLocaltimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLocaltimeLayout.createSequentialGroup()
                .addComponent(lblLocalTime)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpFooterLayout = new javax.swing.GroupLayout(jpFooter);
        jpFooter.setLayout(jpFooterLayout);
        jpFooterLayout.setHorizontalGroup(
            jpFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFooterLayout.createSequentialGroup()
                .addComponent(jpAppName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpLocaltime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jpFooterLayout.setVerticalGroup(
            jpFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpAppName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpLocaltime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu1.setText("Inicio");

        jmuPerfil.setText("Perfil");
        jmuPerfil.setActionCommand("ui_inicio_perfil");
        jMenu1.add(jmuPerfil);

        jmiSalir.setText("Salir");
        jmiSalir.setActionCommand("ui_inicio_salir");
        jMenu1.add(jmiSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Mantenimientos");

        jmiUsuarios.setText("Usuarios");
        jmiUsuarios.setActionCommand("ui_mantenimiento_usuarios");
        jMenu2.add(jmiUsuarios);

        jmiPeliculas.setText("Peliculas");
        jmiPeliculas.setActionCommand("ui_mantenimiento_peliculas");
        jMenu2.add(jmiPeliculas);

        jMenuBar1.add(jMenu2);

        jmiBoleteria.setText("Boleteria");
        jmiBoleteria.setActionCommand("ui_boleteria");
        jMenuBar1.add(jmiBoleteria);

        jmHelp.setText("Ayuda");
        jmHelp.setActionCommand("ui_acerca_de");

        jmiAcercaDe.setText("Acerca de");
        jmiAcercaDe.setActionCommand("ui_ayuda_acerca_de");
        jmHelp.add(jmiAcercaDe);

        jMenuBar1.add(jmHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpMain)
            .addComponent(jpFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdpMain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jdpMain;
    private javax.swing.JMenu jmHelp;
    private javax.swing.JMenuItem jmiAcercaDe;
    private javax.swing.JMenu jmiBoleteria;
    private javax.swing.JMenuItem jmiPeliculas;
    private javax.swing.JMenuItem jmiSalir;
    private javax.swing.JMenuItem jmiUsuarios;
    private javax.swing.JMenuItem jmuPerfil;
    private javax.swing.JPanel jpAppName;
    private javax.swing.JPanel jpFooter;
    private javax.swing.JPanel jpLocaltime;
    private javax.swing.JPanel jpProgressBar;
    private javax.swing.JLabel lblLocalTime;
    // End of variables declaration//GEN-END:variables
}
