/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package pe.edu.utp.poo.application.ui;

/**
 *
 * @author manuelguarniz
 */
public class UISeleccionButacas extends javax.swing.JInternalFrame {

    /**
     * Creates new form UISeleccionButacas
     */
    public UISeleccionButacas() {
        initComponents();
    }
    
    private void continuar() {
        
    }
    
    private void reiniciar() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHorario = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPelicula = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jPanel5 = new javax.swing.JPanel();
        btnContinuar = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnButacaA = new javax.swing.JButton();
        btnButacaB = new javax.swing.JButton();
        btnButacaC = new javax.swing.JButton();
        btnButacaD = new javax.swing.JButton();
        btnButacaE = new javax.swing.JButton();
        btnButacaF = new javax.swing.JButton();
        btnButacaG = new javax.swing.JButton();
        btnButacaH = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        btnButaca12 = new javax.swing.JButton();
        btnButaca1 = new javax.swing.JButton();
        btnButaca2 = new javax.swing.JButton();
        btnButaca3 = new javax.swing.JButton();
        btnButaca4 = new javax.swing.JButton();
        btnButaca5 = new javax.swing.JButton();
        btnButaca6 = new javax.swing.JButton();
        btnButaca7 = new javax.swing.JButton();
        btnButaca8 = new javax.swing.JButton();
        btnButaca9 = new javax.swing.JButton();
        btnButaca10 = new javax.swing.JButton();
        btnButaca11 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        btnButacaA1 = new javax.swing.JButton();
        btnButacaB1 = new javax.swing.JButton();
        btnButacaC1 = new javax.swing.JButton();
        btnButacaD1 = new javax.swing.JButton();
        btnButacaE1 = new javax.swing.JButton();
        btnButacaF1 = new javax.swing.JButton();
        btnButacaG1 = new javax.swing.JButton();
        btnButacaH1 = new javax.swing.JButton();
        btnButacaH2 = new javax.swing.JButton();
        btnButacaH3 = new javax.swing.JButton();
        btnButacaH4 = new javax.swing.JButton();
        btnButacaH5 = new javax.swing.JButton();
        btnButacaG2 = new javax.swing.JButton();
        btnButacaF2 = new javax.swing.JButton();
        btnButacaE2 = new javax.swing.JButton();
        btnButacaD2 = new javax.swing.JButton();
        btnButacaC2 = new javax.swing.JButton();
        btnButacaB2 = new javax.swing.JButton();
        btnButacaA2 = new javax.swing.JButton();
        btnButacaG3 = new javax.swing.JButton();
        btnButacaF3 = new javax.swing.JButton();
        btnButacaE3 = new javax.swing.JButton();
        btnButacaD3 = new javax.swing.JButton();
        btnButacaC3 = new javax.swing.JButton();
        btnButacaB3 = new javax.swing.JButton();
        btnButacaA3 = new javax.swing.JButton();
        btnButacaG4 = new javax.swing.JButton();
        btnButacaF4 = new javax.swing.JButton();
        btnButacaE4 = new javax.swing.JButton();
        btnButacaD4 = new javax.swing.JButton();
        btnButacaC4 = new javax.swing.JButton();
        btnButacaB4 = new javax.swing.JButton();
        btnButacaA4 = new javax.swing.JButton();
        btnButacaG5 = new javax.swing.JButton();
        btnButacaF5 = new javax.swing.JButton();
        btnButacaE5 = new javax.swing.JButton();
        btnButacaD5 = new javax.swing.JButton();
        btnButacaC5 = new javax.swing.JButton();
        btnButacaB5 = new javax.swing.JButton();
        btnButacaA5 = new javax.swing.JButton();
        btnButacaH6 = new javax.swing.JButton();
        btnButacaG6 = new javax.swing.JButton();
        btnButacaF6 = new javax.swing.JButton();
        btnButacaE6 = new javax.swing.JButton();
        btnButacaD6 = new javax.swing.JButton();
        btnButacaC6 = new javax.swing.JButton();
        btnButacaB6 = new javax.swing.JButton();
        btnButacaA6 = new javax.swing.JButton();
        btnButacaG7 = new javax.swing.JButton();
        btnButacaH7 = new javax.swing.JButton();
        btnButacaF7 = new javax.swing.JButton();
        btnButacaE7 = new javax.swing.JButton();
        btnButacaD7 = new javax.swing.JButton();
        btnButacaC7 = new javax.swing.JButton();
        btnButacaB7 = new javax.swing.JButton();
        btnButacaA7 = new javax.swing.JButton();
        btnButacaH8 = new javax.swing.JButton();
        btnButacaF8 = new javax.swing.JButton();
        btnButacaG8 = new javax.swing.JButton();
        btnButacaE8 = new javax.swing.JButton();
        btnButacaD8 = new javax.swing.JButton();
        btnButacaC8 = new javax.swing.JButton();
        btnButacaB8 = new javax.swing.JButton();
        btnButacaA8 = new javax.swing.JButton();
        btnButacaA9 = new javax.swing.JButton();
        btnButacaB9 = new javax.swing.JButton();
        btnButacaC9 = new javax.swing.JButton();
        btnButacaD9 = new javax.swing.JButton();
        btnButacaE9 = new javax.swing.JButton();
        btnButacaF9 = new javax.swing.JButton();
        btnButacaG9 = new javax.swing.JButton();
        btnButacaH9 = new javax.swing.JButton();
        btnButacaA10 = new javax.swing.JButton();
        btnButacaB10 = new javax.swing.JButton();
        btnButacaC10 = new javax.swing.JButton();
        btnButacaD10 = new javax.swing.JButton();
        btnButacaE10 = new javax.swing.JButton();
        btnButacaF10 = new javax.swing.JButton();
        btnButacaG10 = new javax.swing.JButton();
        btnButacaH10 = new javax.swing.JButton();
        btnButacaA11 = new javax.swing.JButton();
        btnButacaB11 = new javax.swing.JButton();
        btnButacaC11 = new javax.swing.JButton();
        btnButacaD11 = new javax.swing.JButton();
        btnButacaE11 = new javax.swing.JButton();
        btnButacaF11 = new javax.swing.JButton();
        btnButacaG11 = new javax.swing.JButton();
        btnButacaH11 = new javax.swing.JButton();
        btnButacaA12 = new javax.swing.JButton();
        btnButacaB12 = new javax.swing.JButton();
        btnButacaC12 = new javax.swing.JButton();
        btnButacaD12 = new javax.swing.JButton();
        btnButacaE12 = new javax.swing.JButton();
        btnButacaF12 = new javax.swing.JButton();
        btnButacaG12 = new javax.swing.JButton();
        btnButacaH12 = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mantenimiento Usuarios");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalles Pelicula"));

        jLabel2.setText("Pelicula:");

        jScrollPane1.setViewportView(txtHorario);

        jLabel3.setText("Horario:");

        jScrollPane2.setViewportView(txtPelicula);

        jLabel4.setText("Niño:");

        jLabel5.setText("Adulto:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        btnReiniciar.setText("Reiniciar");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReiniciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnContinuar)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnContinuar)
                    .addComponent(btnReiniciar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Butacas"));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnButacaA.setText("A");

        btnButacaB.setText("B");

        btnButacaC.setText("C");

        btnButacaD.setText("D");

        btnButacaE.setText("E");

        btnButacaF.setText("F");

        btnButacaG.setText("G");

        btnButacaH.setText("H");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnButacaB)
                    .addComponent(btnButacaC)
                    .addComponent(btnButacaA)
                    .addComponent(btnButacaD)
                    .addComponent(btnButacaE)
                    .addComponent(btnButacaF)
                    .addComponent(btnButacaG)
                    .addComponent(btnButacaH))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnButacaA)
                .addGap(12, 12, 12)
                .addComponent(btnButacaB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnButacaC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnButacaD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnButacaE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnButacaF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnButacaG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnButacaH)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("PANTALLA");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Informativo"));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 121, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnButaca12.setText("12");

        btnButaca1.setText("1");

        btnButaca2.setText("2");

        btnButaca3.setText("3");

        btnButaca4.setText("4");

        btnButaca5.setText("5");

        btnButaca6.setText("6");

        btnButaca7.setText("7");

        btnButaca8.setText("8");

        btnButaca9.setText("9");

        btnButaca10.setText("10");

        btnButaca11.setText("11");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnButaca1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnButaca2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnButaca3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnButaca4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnButaca5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnButaca6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnButaca7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnButaca8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnButaca9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnButaca10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnButaca11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnButaca12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnButaca12)
                    .addComponent(btnButaca1)
                    .addComponent(btnButaca2)
                    .addComponent(btnButaca3)
                    .addComponent(btnButaca4)
                    .addComponent(btnButaca5)
                    .addComponent(btnButaca6)
                    .addComponent(btnButaca7)
                    .addComponent(btnButaca8)
                    .addComponent(btnButaca9)
                    .addComponent(btnButaca10)
                    .addComponent(btnButaca11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnButacaA1.setText(" ");

        btnButacaB1.setText(" ");

        btnButacaC1.setText(" ");

        btnButacaD1.setText(" ");

        btnButacaE1.setText(" ");

        btnButacaF1.setText(" ");

        btnButacaG1.setText(" ");

        btnButacaH1.setText(" ");

        btnButacaH2.setText(" ");

        btnButacaH3.setText(" ");

        btnButacaH4.setText(" ");

        btnButacaH5.setText(" ");

        btnButacaG2.setText(" ");

        btnButacaF2.setText(" ");

        btnButacaE2.setText(" ");

        btnButacaD2.setText(" ");

        btnButacaC2.setText(" ");

        btnButacaB2.setText(" ");

        btnButacaA2.setText(" ");

        btnButacaG3.setText(" ");

        btnButacaF3.setText(" ");

        btnButacaE3.setText(" ");

        btnButacaD3.setText(" ");

        btnButacaC3.setText(" ");

        btnButacaB3.setText(" ");

        btnButacaA3.setText(" ");

        btnButacaG4.setText(" ");

        btnButacaF4.setText(" ");

        btnButacaE4.setText(" ");

        btnButacaD4.setText(" ");

        btnButacaC4.setText(" ");

        btnButacaB4.setText(" ");

        btnButacaA4.setText(" ");

        btnButacaG5.setText(" ");

        btnButacaF5.setText(" ");

        btnButacaE5.setText(" ");

        btnButacaD5.setText(" ");

        btnButacaC5.setText(" ");

        btnButacaB5.setText(" ");

        btnButacaA5.setForeground(new java.awt.Color(153, 204, 255));
        btnButacaA5.setText(" ");

        btnButacaH6.setText(" ");

        btnButacaG6.setText(" ");

        btnButacaF6.setText(" ");

        btnButacaE6.setText(" ");

        btnButacaD6.setText(" ");

        btnButacaC6.setText(" ");

        btnButacaB6.setText(" ");

        btnButacaA6.setText(" ");

        btnButacaG7.setText(" ");

        btnButacaH7.setText(" ");

        btnButacaF7.setText(" ");

        btnButacaE7.setText(" ");

        btnButacaD7.setText(" ");

        btnButacaC7.setText(" ");

        btnButacaB7.setText(" ");

        btnButacaA7.setText(" ");

        btnButacaH8.setText(" ");

        btnButacaF8.setText(" ");

        btnButacaG8.setText(" ");

        btnButacaE8.setText(" ");

        btnButacaD8.setText(" ");

        btnButacaC8.setText(" ");

        btnButacaB8.setText(" ");

        btnButacaA8.setText(" ");

        btnButacaA9.setText(" ");

        btnButacaB9.setText(" ");

        btnButacaC9.setText(" ");

        btnButacaD9.setText(" ");

        btnButacaE9.setText(" ");

        btnButacaF9.setText(" ");

        btnButacaG9.setText(" ");

        btnButacaH9.setText(" ");

        btnButacaA10.setText(" ");

        btnButacaB10.setText(" ");

        btnButacaC10.setText(" ");

        btnButacaD10.setText(" ");

        btnButacaE10.setText(" ");

        btnButacaF10.setText(" ");

        btnButacaG10.setText(" ");

        btnButacaH10.setText(" ");

        btnButacaA11.setText(" ");

        btnButacaB11.setText(" ");

        btnButacaC11.setText(" ");

        btnButacaD11.setText(" ");

        btnButacaE11.setText(" ");

        btnButacaF11.setText(" ");

        btnButacaG11.setText(" ");

        btnButacaH11.setText(" ");

        btnButacaA12.setText(" ");

        btnButacaB12.setText(" ");

        btnButacaC12.setText(" ");

        btnButacaD12.setText(" ");

        btnButacaE12.setText(" ");

        btnButacaF12.setText(" ");

        btnButacaG12.setText(" ");

        btnButacaH12.setText(" ");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnButacaD1, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                            .addComponent(btnButacaE1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnButacaH1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnButacaG1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnButacaF1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnButacaD2, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                            .addComponent(btnButacaE2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnButacaH2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnButacaG2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnButacaF2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnButacaD3, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                            .addComponent(btnButacaE3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnButacaF3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnButacaG3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnButacaH3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnButacaD4, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                            .addComponent(btnButacaE4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnButacaF4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnButacaG4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnButacaH4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnButacaA1, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                            .addComponent(btnButacaB1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnButacaC1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnButacaB2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                            .addComponent(btnButacaA2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnButacaC2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnButacaB3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnButacaC3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnButacaA3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnButacaC4, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                            .addComponent(btnButacaB4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnButacaA4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(btnButacaF5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnButacaF6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel11Layout.createSequentialGroup()
                            .addComponent(btnButacaA5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnButacaA6, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                        .addGroup(jPanel11Layout.createSequentialGroup()
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnButacaH5, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                .addComponent(btnButacaG5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnButacaH6, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                .addComponent(btnButacaG6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel11Layout.createSequentialGroup()
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnButacaE5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                .addComponent(btnButacaD5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnButacaC5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnButacaB5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnButacaD6, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                .addComponent(btnButacaC6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnButacaB6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnButacaE6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnButacaB7, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btnButacaA7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnButacaC7, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btnButacaD7, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btnButacaE7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnButacaF7, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btnButacaG7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnButacaH7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnButacaB8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btnButacaC8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnButacaD8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnButacaE8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnButacaG8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnButacaF8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnButacaA8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnButacaH8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnButacaB9, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btnButacaA9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnButacaC9, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btnButacaD9, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btnButacaE9, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btnButacaF9, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btnButacaG9, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btnButacaH9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnButacaA10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnButacaB10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnButacaC10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnButacaD10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnButacaE10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnButacaF10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnButacaG10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(btnButacaH10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnButacaA11, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btnButacaB11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnButacaC11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnButacaD11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnButacaE11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnButacaF11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnButacaG11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnButacaH11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnButacaA12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnButacaB12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnButacaC12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnButacaD12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btnButacaE12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnButacaF12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnButacaG12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnButacaH12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnButacaA1)
                    .addComponent(btnButacaA2)
                    .addComponent(btnButacaA3)
                    .addComponent(btnButacaA4)
                    .addComponent(btnButacaA5)
                    .addComponent(btnButacaA6)
                    .addComponent(btnButacaA7)
                    .addComponent(btnButacaA8)
                    .addComponent(btnButacaA9)
                    .addComponent(btnButacaA10)
                    .addComponent(btnButacaA11)
                    .addComponent(btnButacaA12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnButacaB1)
                    .addComponent(btnButacaB2)
                    .addComponent(btnButacaB3)
                    .addComponent(btnButacaB4)
                    .addComponent(btnButacaB5)
                    .addComponent(btnButacaB6)
                    .addComponent(btnButacaB7)
                    .addComponent(btnButacaB8)
                    .addComponent(btnButacaB9)
                    .addComponent(btnButacaB10)
                    .addComponent(btnButacaB11)
                    .addComponent(btnButacaB12))
                .addGap(12, 12, 12)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnButacaC1)
                    .addComponent(btnButacaC2)
                    .addComponent(btnButacaC3)
                    .addComponent(btnButacaC4)
                    .addComponent(btnButacaC5)
                    .addComponent(btnButacaC6)
                    .addComponent(btnButacaC7)
                    .addComponent(btnButacaC8)
                    .addComponent(btnButacaC9)
                    .addComponent(btnButacaC10)
                    .addComponent(btnButacaC11)
                    .addComponent(btnButacaC12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnButacaD1)
                    .addComponent(btnButacaD2)
                    .addComponent(btnButacaD3)
                    .addComponent(btnButacaD4)
                    .addComponent(btnButacaD5)
                    .addComponent(btnButacaD6)
                    .addComponent(btnButacaD7)
                    .addComponent(btnButacaD8)
                    .addComponent(btnButacaD9)
                    .addComponent(btnButacaD10)
                    .addComponent(btnButacaD11)
                    .addComponent(btnButacaD12))
                .addGap(12, 12, 12)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnButacaE1)
                    .addComponent(btnButacaE2)
                    .addComponent(btnButacaE3)
                    .addComponent(btnButacaE4)
                    .addComponent(btnButacaE5)
                    .addComponent(btnButacaE6)
                    .addComponent(btnButacaE7)
                    .addComponent(btnButacaE8)
                    .addComponent(btnButacaE9)
                    .addComponent(btnButacaE10)
                    .addComponent(btnButacaE11)
                    .addComponent(btnButacaE12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnButacaF1)
                    .addComponent(btnButacaF2)
                    .addComponent(btnButacaF3)
                    .addComponent(btnButacaF4)
                    .addComponent(btnButacaF5)
                    .addComponent(btnButacaF6)
                    .addComponent(btnButacaF7)
                    .addComponent(btnButacaF8)
                    .addComponent(btnButacaF9)
                    .addComponent(btnButacaF10)
                    .addComponent(btnButacaF11)
                    .addComponent(btnButacaF12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnButacaG1)
                    .addComponent(btnButacaG2)
                    .addComponent(btnButacaG3)
                    .addComponent(btnButacaG4)
                    .addComponent(btnButacaG5)
                    .addComponent(btnButacaG6)
                    .addComponent(btnButacaG7)
                    .addComponent(btnButacaG8)
                    .addComponent(btnButacaG9)
                    .addComponent(btnButacaG10)
                    .addComponent(btnButacaG11)
                    .addComponent(btnButacaG12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnButacaH1)
                    .addComponent(btnButacaH2)
                    .addComponent(btnButacaH3)
                    .addComponent(btnButacaH4)
                    .addComponent(btnButacaH5)
                    .addComponent(btnButacaH6)
                    .addComponent(btnButacaH7)
                    .addComponent(btnButacaH8)
                    .addComponent(btnButacaH9)
                    .addComponent(btnButacaH10)
                    .addComponent(btnButacaH11)
                    .addComponent(btnButacaH12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        continuar();
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        reiniciar();
    }//GEN-LAST:event_btnReiniciarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnButaca1;
    private javax.swing.JButton btnButaca10;
    private javax.swing.JButton btnButaca11;
    private javax.swing.JButton btnButaca12;
    private javax.swing.JButton btnButaca2;
    private javax.swing.JButton btnButaca3;
    private javax.swing.JButton btnButaca4;
    private javax.swing.JButton btnButaca5;
    private javax.swing.JButton btnButaca6;
    private javax.swing.JButton btnButaca7;
    private javax.swing.JButton btnButaca8;
    private javax.swing.JButton btnButaca9;
    private javax.swing.JButton btnButacaA;
    private javax.swing.JButton btnButacaA1;
    private javax.swing.JButton btnButacaA10;
    private javax.swing.JButton btnButacaA11;
    private javax.swing.JButton btnButacaA12;
    private javax.swing.JButton btnButacaA2;
    private javax.swing.JButton btnButacaA3;
    private javax.swing.JButton btnButacaA4;
    private javax.swing.JButton btnButacaA5;
    private javax.swing.JButton btnButacaA6;
    private javax.swing.JButton btnButacaA7;
    private javax.swing.JButton btnButacaA8;
    private javax.swing.JButton btnButacaA9;
    private javax.swing.JButton btnButacaB;
    private javax.swing.JButton btnButacaB1;
    private javax.swing.JButton btnButacaB10;
    private javax.swing.JButton btnButacaB11;
    private javax.swing.JButton btnButacaB12;
    private javax.swing.JButton btnButacaB2;
    private javax.swing.JButton btnButacaB3;
    private javax.swing.JButton btnButacaB4;
    private javax.swing.JButton btnButacaB5;
    private javax.swing.JButton btnButacaB6;
    private javax.swing.JButton btnButacaB7;
    private javax.swing.JButton btnButacaB8;
    private javax.swing.JButton btnButacaB9;
    private javax.swing.JButton btnButacaC;
    private javax.swing.JButton btnButacaC1;
    private javax.swing.JButton btnButacaC10;
    private javax.swing.JButton btnButacaC11;
    private javax.swing.JButton btnButacaC12;
    private javax.swing.JButton btnButacaC2;
    private javax.swing.JButton btnButacaC3;
    private javax.swing.JButton btnButacaC4;
    private javax.swing.JButton btnButacaC5;
    private javax.swing.JButton btnButacaC6;
    private javax.swing.JButton btnButacaC7;
    private javax.swing.JButton btnButacaC8;
    private javax.swing.JButton btnButacaC9;
    private javax.swing.JButton btnButacaD;
    private javax.swing.JButton btnButacaD1;
    private javax.swing.JButton btnButacaD10;
    private javax.swing.JButton btnButacaD11;
    private javax.swing.JButton btnButacaD12;
    private javax.swing.JButton btnButacaD2;
    private javax.swing.JButton btnButacaD3;
    private javax.swing.JButton btnButacaD4;
    private javax.swing.JButton btnButacaD5;
    private javax.swing.JButton btnButacaD6;
    private javax.swing.JButton btnButacaD7;
    private javax.swing.JButton btnButacaD8;
    private javax.swing.JButton btnButacaD9;
    private javax.swing.JButton btnButacaE;
    private javax.swing.JButton btnButacaE1;
    private javax.swing.JButton btnButacaE10;
    private javax.swing.JButton btnButacaE11;
    private javax.swing.JButton btnButacaE12;
    private javax.swing.JButton btnButacaE2;
    private javax.swing.JButton btnButacaE3;
    private javax.swing.JButton btnButacaE4;
    private javax.swing.JButton btnButacaE5;
    private javax.swing.JButton btnButacaE6;
    private javax.swing.JButton btnButacaE7;
    private javax.swing.JButton btnButacaE8;
    private javax.swing.JButton btnButacaE9;
    private javax.swing.JButton btnButacaF;
    private javax.swing.JButton btnButacaF1;
    private javax.swing.JButton btnButacaF10;
    private javax.swing.JButton btnButacaF11;
    private javax.swing.JButton btnButacaF12;
    private javax.swing.JButton btnButacaF2;
    private javax.swing.JButton btnButacaF3;
    private javax.swing.JButton btnButacaF4;
    private javax.swing.JButton btnButacaF5;
    private javax.swing.JButton btnButacaF6;
    private javax.swing.JButton btnButacaF7;
    private javax.swing.JButton btnButacaF8;
    private javax.swing.JButton btnButacaF9;
    private javax.swing.JButton btnButacaG;
    private javax.swing.JButton btnButacaG1;
    private javax.swing.JButton btnButacaG10;
    private javax.swing.JButton btnButacaG11;
    private javax.swing.JButton btnButacaG12;
    private javax.swing.JButton btnButacaG2;
    private javax.swing.JButton btnButacaG3;
    private javax.swing.JButton btnButacaG4;
    private javax.swing.JButton btnButacaG5;
    private javax.swing.JButton btnButacaG6;
    private javax.swing.JButton btnButacaG7;
    private javax.swing.JButton btnButacaG8;
    private javax.swing.JButton btnButacaG9;
    private javax.swing.JButton btnButacaH;
    private javax.swing.JButton btnButacaH1;
    private javax.swing.JButton btnButacaH10;
    private javax.swing.JButton btnButacaH11;
    private javax.swing.JButton btnButacaH12;
    private javax.swing.JButton btnButacaH2;
    private javax.swing.JButton btnButacaH3;
    private javax.swing.JButton btnButacaH4;
    private javax.swing.JButton btnButacaH5;
    private javax.swing.JButton btnButacaH6;
    private javax.swing.JButton btnButacaH7;
    private javax.swing.JButton btnButacaH8;
    private javax.swing.JButton btnButacaH9;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTextPane txtHorario;
    private javax.swing.JTextPane txtPelicula;
    // End of variables declaration//GEN-END:variables
}
